# -*- coding: utf-8 -*-
"""ADBrainNet_structure.ipynb

Automatically generated by Colab.
"""


"""
Note: "*" means thos parameter can be adjusted according to your specific tasks.
"""


import os
import subprocess
import tensorflow as tf
import numpy as np
import random
import os
import time
import shutil
import warnings
import math
from sklearn.model_selection import KFold
from tensorflow.keras.applications import MobileNet
from tensorflow.keras.models import Model, Sequential
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras import optimizers, losses, metrics
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint, Callback
from keras.regularizers import l2
from tensorflow.keras.layers import (
Conv2D, MaxPooling2D, Dropout, Flatten, Dense,
BatchNormalization, GlobalAveragePooling2D,
Add, Activation, Input, AveragePooling2D, Concatenate, Multiply, Layer
)
import keras.backend as K


#random seed
seed = 42
tf.random.set_seed(seed)
np.random.seed(seed)
random.seed(seed)

#warnings
warnings.filterwarnings("ignore")


base_dir = '/content/your dataset path/'
training_dir = os.path.join(base_dir,'training_dir')
validation_dir = os.path.join(base_dir,'validation_dir')
testing_dir = os.path.join(base_dir,'testing_dir')


classes = ['ADHD combined', 'ADHD hyperactive impulsive', 'ADHD inattentive', 'ASD', 'neurotypical']

# merge training dataset and validation dataset
merged_dir = '/content/merged_data_adbrainnet_final_model'
if not os.path.exists(merged_dir):
    os.makedirs(merged_dir)

for class_name in classes:
    class_merged_dir = os.path.join(merged_dir, class_name)
    if not os.path.exists(class_merged_dir):
        os.makedirs(class_merged_dir)

    train_class_dir = os.path.join(training_dir, class_name)
    for img in os.listdir(train_class_dir):
        src = os.path.join(train_class_dir, img)
        dst = os.path.join(class_merged_dir, img)
        shutil.copy2(src, dst)

    val_class_dir = os.path.join(validation_dir, class_name)
    for img in os.listdir(val_class_dir):
        src = os.path.join(val_class_dir, img)
        dst = os.path.join(class_merged_dir, img)
        shutil.copy2(src, dst)


# ==================== SENetLayer ====================
class SENetLayer(Layer):
    def __init__(self, ratio=*, **kwargs):
        super(SENetLayer, self).__init__(**kwargs)
        self.ratio = ratio

    def build(self, input_shape):
        channel_axis = * if K.image_data_format() == "channels_first" else -1
        channel_count = input_shape[channel_axis]

        self.global_avg_pool = GlobalAveragePooling2D()
        self.dense_1 = Dense(channel_count // self.ratio, activation='relu',
                            kernel_regularizer=l2(*), use_bias=False)
        self.dense_2 = Dense(channel_count, activation='sigmoid',
                            kernel_regularizer=l2(*), use_bias=False)
        self.multiply = Multiply()
        super(SENetLayer, self).build(input_shape)

    def call(self, inputs):
        se_feature = self.global_avg_pool(inputs)
        se_feature = self.dense_1(se_feature)
        se_feature = self.dense_2(se_feature)
        x = self.multiply([inputs, se_feature])
        return x

    def get_config(self):
        config = super().get_config()
        config.update({"ratio": self.ratio})
        return config


# ==================== Residual Block ====================
class EnhancedResidualBlock(Layer):
    """Enhancement block combining residual connections and multi-scale features"""
    def __init__(self, filters, kernel_size=3, use_se=True, **kwargs):
        super(EnhancedResidualBlock, self).__init__(**kwargs)
        self.filters = filters
        self.kernel_size = kernel_size
        self.use_se = use_se

    def build(self, input_shape):
        # main branch
        self.conv1 = Conv2D(self.filters, self.kernel_size, padding='same',
                           kernel_regularizer=l2(*))
        self.bn1 = BatchNormalization()

        self.conv2 = Conv2D(self.filters, self.kernel_size, padding='same',
                           kernel_regularizer=l2(*))
        self.bn2 = BatchNormalization()

        # multi-scale features
        self.conv3x3 = Conv2D(self.filters//*, *, padding='same')
        self.conv5x5 = Conv2D(self.filters//*, *, padding='same')
        self.conv1x1 = Conv2D(self.filters//*, *, padding='same')

        self.bn_ms = BatchNormalization()
        self.activation_ms = Activation('relu')

        self.concat = Concatenate()
        self.add_ms = Add() 

        if self.use_se:
            self.se = SENetLayer(ratio=*)

        # shortcut
        self.shortcut_conv = Conv2D(self.filters, 1, padding='same')
        self.shortcut_bn = BatchNormalization()

        self.add_residual = Add()
        self.activation_out = Activation('relu')

        super().build(input_shape)

    def call(self, inputs):
        # main path
        x = self.conv1(inputs)
        x = self.bn1(x)
        x = Activation('relu')(x)

        x = self.conv2(x)
        x = self.bn2(x)

        branch1 = self.conv*x*(x)
        branch2 = self.conv*x*(x)
        branch3 = self.conv*x*(x)

        multi_scale = self.concat([branch1, branch2, branch3])
        multi_scale = self.bn_ms(multi_scale)
        multi_scale = self.activation_ms(multi_scale)

        x = self.add_ms([x, multi_scale])

        # attention layers
        if self.use_se:
            x = self.se(x)

        shortcut = self.shortcut_conv(inputs)
        shortcut = self.shortcut_bn(shortcut)

        # final output
        output = self.add_residual([x, shortcut])
        output = self.activation_out(output)

        return output

    def get_config(self):
        config = super().get_config()
        config.update({
            'filters': self.filters,
            'kernel_size': self.kernel_size,
            'use_se': self.use_se
        })
        return config

# model structure
def build_cnn_model(input_shape=your_shape, num_classes= your classes, learning_rate= your learning rate):
   
    model = Sequential()

    model.add(Conv2D(*, (*, *), strides=*, padding='same',
                     activation='relu', input_shape=input_shape,
                     kernel_regularizer=l2(*)))
    model.add(BatchNormalization())
    model.add(MaxPooling2D((*, *), strides=*, padding='same'))
    model.add(Dropout(*)) 

    # ========== Stage 2 ==========
    model.add(EnhancedResidualBlock(*, use_se=True))
    model.add(MaxPooling2D((*, *)))
    model.add(Dropout(*))

    # ========== Stage 3 ==========
    model.add(EnhancedResidualBlock(*, use_se=True))
    model.add(MaxPooling2D((*, *)))
    model.add(Dropout(*))

    # ========== Stage 4 ==========
    model.add(EnhancedResidualBlock(*, use_se=True))
    model.add(AveragePooling2D((*, *)))
    model.add(Dropout(*))

    # ========== Stage 5 ==========
    model.add(EnhancedResidualBlock(*, use_se=True))
    model.add(GlobalAveragePooling2D())
    model.add(Dropout(*))

    # dense layers
    model.add(Dense(*, activation='relu', kernel_regularizer=l2(*)))
    model.add(BatchNormalization())
    model.add(Dropout(*))

    model.add(Dense(*, activation='relu', kernel_regularizer=l2(*)))
    model.add(BatchNormalization())
    model.add(Dropout(*))

    model.add(Dense(*, activation='relu', kernel_regularizer=l2(1e-5)))
    model.add(BatchNormalization())
    model.add(Dropout(*))

    # final output
    model.add(Dense(num_classes, activation='softmax'))

    model.compile(optimizer=optimizers.Adam(learning_rate=learning_rate),
                         loss=losses.categorical_crossentropy,
                         metrics=[metrics.CategoricalAccuracy(), metrics.Precision(), metrics.Recall(),
                                 ])

    return model

image_paths = []
labels = []
class_indices = {}

for i, class_name in enumerate(classes):
    class_dir = os.path.join(merged_dir, class_name)
    class_indices[class_name] = i
    for img in os.listdir(class_dir):
        image_paths.append(os.path.join(class_dir, img))
        labels.append(i)


image_paths = np.array(image_paths)
labels = np.array(labels)

from sklearn.model_selection import KFold
import pandas as pd
import os
import numpy as np
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, Callback, CSVLogger
from keras.models import load_model
from tensorflow.keras import backend as K
import random
import numpy as np
import tensorflow as tf
from PIL import Image, ImageEnhance
from sklearn.model_selection import KFold
import os
from sklearn.model_selection import StratifiedKFold
import shutil
from keras.utils import custom_object_scope


# ============  training fold ============
start_fold = 1  
print(f"start from {start_fold} ")
# ============ end ============


def apply_class_specific_augmentation(img_path, label, num_augmentations, base_seed):
    """
    different data augmentation for different groups

    """
        return augmented_images



class SaveModelEachEpoch(Callback):
    def __init__(self, save_dir, fold_num):
        super(SaveModelEachEpoch, self).__init__()
        self.save_dir = save_dir
        self.fold_num = fold_num

    def on_epoch_end(self, epoch, logs=None):
        epoch_model_path = os.path.join(
            self.save_dir,
            f'fold_{self.fold_num}_epoch_{epoch+1:03d}.h5'
        )
        self.model.save(epoch_model_path)
        print(f'Fold {self.fold_num} - Epoch {epoch+1}: model save as {epoch_model_path}')


epoch_models_dir = '/content/your path'
if not os.path.exists(epoch_models_dir):
    os.makedirs(epoch_models_dir)
    print(f"epoch content: {epoch_models_dir}")

epoch_metrics_dir = '/content/your path'
if not os.path.exists(epoch_metrics_dir):
    os.makedirs(epoch_metrics_dir)
    print(f"epoch content: {epoch_metrics_dir}")


datagen = ImageDataGenerator(rescale=1./255)

random.seed(42)
np.random.seed(42)
tf.random.set_seed(42)
os.environ['PYTHONHASHSEED'] = str(42)


# Kfold initialize
kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
fold_no = 1
fold_results = []

# 5 fold validation
for train_idx, val_idx in kfold.split(image_paths, labels):
    if fold_no < start_fold:
        print(f'\n{"="*50}')
        print(f'skip Fold {fold_no} (Start from Fold {start_fold} )')
        print(f'{"="*50}')
        fold_no += 1
        continue

    print(f'\n{"="*50}')
    print(f'Training Fold {fold_no}')
    print(f'{"="*50}')

    temp_train_dir = f'/content/fold_{fold_no}_train'
    temp_val_dir = f'/content/fold_{fold_no}_val'

    if os.path.exists(temp_train_dir):
        shutil.rmtree(temp_train_dir)
    if os.path.exists(temp_val_dir):
        shutil.rmtree(temp_val_dir)

    for class_name in classes:
        os.makedirs(os.path.join(temp_train_dir, class_name), exist_ok=True)
        os.makedirs(os.path.join(temp_val_dir, class_name), exist_ok=True)

    for idx in train_idx:
        img_path = image_paths[idx]
        label = labels[idx]
        class_name = classes[label]

        shutil.copy2(img_path, os.path.join(temp_train_dir, class_name))

        """
        decide the multiple of datat augmentation

        """
        
        for aug_idx, aug_img in enumerate(augmented_images):
            original_filename = os.path.basename(img_path)
            transformed_file_name = os.path.splitext(original_filename)[0] + f'_aug{aug_idx}.jpg'
            save_path = os.path.join(temp_train_dir, class_name, transformed_file_name)
            aug_img.save(save_path, 'png')
            
    for idx in val_idx:
        img_path = image_paths[idx]
        label = labels[idx]
        class_name = classes[label]
        shutil.copy2(img_path, os.path.join(temp_val_dir, class_name))

    train_generator = datagen.flow_from_directory(
        temp_train_dir,
        target_size=(*, *),
        batch_size=*,
        class_mode='categorical'
    )

    val_generator = datagen.flow_from_directory(
        temp_val_dir,
        target_size=(*, *),
        batch_size=*,
        class_mode='categorical',
        shuffle=False
    )

    model = build_cnn_model()


    csv_logger = CSVLogger(
      os.path.join(epoch_metrics_dir, f'fold_{fold_no}_epoch_metrics.csv'),
      separator=',',
      append=True 
    )

    class_weights = your classweight


    early_stopping = EarlyStopping(monitor='val_loss', patience=20, verbose=1, restore_best_weights=True)
    lr_reduction = ReduceLROnPlateau(monitor='val_loss', patience=5, verbose=1, factor=0.2)


    history = model.fit(
        train_generator,
        class_weight=class_weights,
        steps_per_epoch=math.ceil(train_generator.samples / train_generator.batch_size),
        epochs=your epoch,
        validation_data=val_generator,
        validation_steps=math.ceil(val_generator.samples / val_generator.batch_size),
        #AdjustValidationClassWeights(val_generator, initial_val_weights),
        callbacks=[
            lr_reduction,
            early_stopping,
            save_each_epoch,    
            csv_logger        
        ],
        verbose=2
    )

   
