# -*- coding: utf-8 -*-
"""ADBrainNet_final_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y3nOJbcWfOiIMkdeai3d2EV1716LyKot
"""

pip install tensorflow==2.19.0

import os
import subprocess

# 1. 先尝试卸载已挂载的 Drive
try:
    # 卸载命令
    !fusermount -u /content/drive
    print("✅ 已卸载 /content/drive")
except Exception as e:
    print(f"卸载时出现警告: {e}")

# 2. 等待一下
import time
time.sleep(2)

# 3. 确保挂载点目录存在且为空
!rm -rf /content/drive  # 删除旧的挂载点目录
!mkdir /content/drive   # 创建新的空目录

# 4. 现在重新挂载
from google.colab import drive
drive.mount('/content/drive')

import tensorflow as tf
import numpy as np
import random
import os
import time
import shutil
import warnings
from sklearn.model_selection import KFold
from tensorflow.keras.applications import MobileNet
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D, Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras import optimizers, losses, metrics
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint
from tensorflow.keras.callbacks import Callback
from keras.regularizers import l2
#import tensorflow_addons as tfa
import math

# 设置随机种子
seed = 42
tf.random.set_seed(seed)
np.random.seed(seed)
random.seed(seed)

warnings.filterwarnings("ignore")

# 数据所在的文件夹
base_dir = '/content/drive/My Drive/ASD ADHD revision/final dataset/'
training_dir = os.path.join(base_dir,'training_dir')
validation_dir = os.path.join(base_dir,'validation_dir')
testing_dir = os.path.join(base_dir,'testing_dir')

# 自定义回调函数
class AdjustValidationClassWeights(Callback):
    def __init__(self, validation_generator, new_weights, interval=5):
        super(AdjustValidationClassWeights, self).__init__()
        self.validation_generator = validation_generator
        self.new_weights = new_weights
        self.interval = interval
        self.counter = 0

    def on_epoch_end(self, epoch, logs=None):
        self.counter += 1
        if self.counter % self.interval == 0:
            self.validation_generator.class_weights = self.new_weights
            self.counter = 0

#类别列表
classes = ['ADHD combined', 'ADHD hyperactive impulsive', 'ADHD inattentive', 'ASD', 'neurotypical']

# 1. 合并训练集和验证集用于交叉验证
merged_dir = '/content/merged_data_adbrainnet_final_model'
if not os.path.exists(merged_dir):
    os.makedirs(merged_dir)

for class_name in classes:
    class_merged_dir = os.path.join(merged_dir, class_name)
    if not os.path.exists(class_merged_dir):
        os.makedirs(class_merged_dir)

    # 复制训练集数据
    train_class_dir = os.path.join(training_dir, class_name)
    for img in os.listdir(train_class_dir):
        src = os.path.join(train_class_dir, img)
        dst = os.path.join(class_merged_dir, img)
        shutil.copy2(src, dst)

    # 复制验证集数据
    val_class_dir = os.path.join(validation_dir, class_name)
    for img in os.listdir(val_class_dir):
        src = os.path.join(val_class_dir, img)
        dst = os.path.join(class_merged_dir, img)
        shutil.copy2(src, dst)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import (
    Conv2D, MaxPooling2D, Dropout, Flatten, Dense,
    BatchNormalization, GlobalAveragePooling2D,
    Add, Activation, Input, AveragePooling2D, Concatenate
)
from tensorflow.keras.regularizers import l2
import tensorflow as tf
from tensorflow.keras.layers import Multiply, Layer
import keras.backend as K


# ==================== 保留你的SENetLayer ====================
class SENetLayer(Layer):
    def __init__(self, ratio=16, **kwargs):
        super(SENetLayer, self).__init__(**kwargs)
        self.ratio = ratio

    def build(self, input_shape):
        channel_axis = 1 if K.image_data_format() == "channels_first" else -1
        channel_count = input_shape[channel_axis]

        self.global_avg_pool = GlobalAveragePooling2D()
        self.dense_1 = Dense(channel_count // self.ratio, activation='relu',
                            kernel_regularizer=l2(1e-5), use_bias=False)
        self.dense_2 = Dense(channel_count, activation='sigmoid',
                            kernel_regularizer=l2(1e-5), use_bias=False)
        self.multiply = Multiply()
        super(SENetLayer, self).build(input_shape)

    def call(self, inputs):
        se_feature = self.global_avg_pool(inputs)
        se_feature = self.dense_1(se_feature)
        se_feature = self.dense_2(se_feature)
        x = self.multiply([inputs, se_feature])
        return x

    def get_config(self):
        config = super().get_config()
        config.update({"ratio": self.ratio})
        return config

# ==================== 新增：增强的残差注意力块 ====================
class EnhancedResidualBlock(Layer):
    """结合残差连接和多尺度特征的增强块"""
    def __init__(self, filters, kernel_size=3, use_se=True, **kwargs):
        super(EnhancedResidualBlock, self).__init__(**kwargs)
        self.filters = filters
        self.kernel_size = kernel_size
        self.use_se = use_se

    def build(self, input_shape):
        # 主路径：两个卷积层
        self.conv1 = Conv2D(self.filters, self.kernel_size, padding='same',
                           kernel_regularizer=l2(1e-5))
        self.bn1 = BatchNormalization()

        self.conv2 = Conv2D(self.filters, self.kernel_size, padding='same',
                           kernel_regularizer=l2(1e-5))
        self.bn2 = BatchNormalization()

        # 多尺度特征提取
        self.conv3x3 = Conv2D(self.filters//4, 3, padding='same')
        self.conv5x5 = Conv2D(self.filters//4, 5, padding='same')
        self.conv1x1 = Conv2D(self.filters//2, 1, padding='same')

        # ========== 新增：在这里创建缺失的层 ==========
        # 多尺度特征的BN和激活
        self.bn_ms = BatchNormalization()
        self.activation_ms = Activation('relu')

        # 合并多尺度特征
        self.concat = Concatenate()
        self.add_ms = Add()  # 用于合并多尺度特征

        # 注意力
        if self.use_se:
            self.se = SENetLayer(ratio=16)

        # 快捷连接
        self.shortcut_conv = Conv2D(self.filters, 1, padding='same')
        self.shortcut_bn = BatchNormalization()

        # ========== 新增：残差合并层 ==========
        self.add_residual = Add()
        self.activation_out = Activation('relu')

        super().build(input_shape)

    def call(self, inputs):
        # 主路径
        x = self.conv1(inputs)
        x = self.bn1(x)
        x = Activation('relu')(x)

        x = self.conv2(x)
        x = self.bn2(x)

        # 多尺度特征
        branch1 = self.conv3x3(x)
        branch2 = self.conv5x5(x)
        branch3 = self.conv1x1(x)

        # 合并多尺度特征
        multi_scale = self.concat([branch1, branch2, branch3])
        multi_scale = self.bn_ms(multi_scale)
        multi_scale = self.activation_ms(multi_scale)

        # 与主路径融合 - 使用在build中创建的层
        x = self.add_ms([x, multi_scale])

        # SE注意力
        if self.use_se:
            x = self.se(x)

        # 残差连接
        shortcut = self.shortcut_conv(inputs)
        shortcut = self.shortcut_bn(shortcut)

        # 最终输出 - 使用在build中创建的层
        output = self.add_residual([x, shortcut])
        output = self.activation_out(output)

        return output

    def get_config(self):
        config = super().get_config()
        config.update({
            'filters': self.filters,
            'kernel_size': self.kernel_size,
            'use_se': self.use_se
        })
        return config

# ==================== 新的模型架构 ====================
def build_cnn_model(input_shape=(64, 64, 3), num_classes=5, learning_rate=0.0002):
    """
    增强的ADBrainNet架构
    核心改进：
    1. 多尺度特征提取
    2. 残差连接（避免梯度消失）
    3. 渐进式特征融合
    4. 增强的SE注意力
    """
    model = Sequential()

    # ========== Stage 1: 高分辨率特征提取 ==========
    # 使用大卷积核捕获更大感受野
    model.add(Conv2D(32, (7, 7), strides=2, padding='same',
                     activation='relu', input_shape=input_shape,
                     kernel_regularizer=l2(1e-5)))
    model.add(BatchNormalization())
    model.add(MaxPooling2D((3, 3), strides=2, padding='same'))
    model.add(Dropout(0.1))  # 低层减少dropout

    # ========== Stage 2: 多尺度特征学习 ==========
    # 增强残差块1
    model.add(EnhancedResidualBlock(64, use_se=True))
    model.add(MaxPooling2D((2, 2)))
    model.add(Dropout(0.15))

    # ========== Stage 3: 中级特征抽象 ==========
    model.add(EnhancedResidualBlock(128, use_se=True))
    model.add(MaxPooling2D((2, 2)))
    model.add(Dropout(0.2))

    # ========== Stage 4: 高级特征抽象 ==========
    model.add(EnhancedResidualBlock(256, use_se=True))
    # 这里不用MaxPooling，用平均池化保留更多空间信息
    model.add(AveragePooling2D((2, 2)))
    model.add(Dropout(0.25))

    # ========== Stage 5: 特征精炼 ==========
    model.add(EnhancedResidualBlock(512, use_se=True))
    # 全局平均池化替代Flatten，减少参数防止过拟合
    model.add(GlobalAveragePooling2D())
    model.add(Dropout(0.3))

    # ========== 特征融合层 ==========
    # 使用多个全连接层进行渐进式特征融合
    model.add(Dense(1024, activation='relu', kernel_regularizer=l2(1e-5)))
    model.add(BatchNormalization())
    model.add(Dropout(0.4))

    model.add(Dense(512, activation='relu', kernel_regularizer=l2(1e-5)))
    model.add(BatchNormalization())
    model.add(Dropout(0.35))

    # 添加一个瓶颈层，强制模型学习压缩表示
    model.add(Dense(256, activation='relu', kernel_regularizer=l2(1e-5)))
    model.add(BatchNormalization())
    model.add(Dropout(0.3))

    # 输出层
    model.add(Dense(num_classes, activation='softmax'))

    model.compile(optimizer=optimizers.Adam(learning_rate=learning_rate),
                         loss=losses.categorical_crossentropy,
                         metrics=[metrics.CategoricalAccuracy(), metrics.Precision(), metrics.Recall(),
                                 ])

    return model

#收集所有图像路径和标签
image_paths = []
labels = []
class_indices = {}

for i, class_name in enumerate(classes):
    class_dir = os.path.join(merged_dir, class_name)
    class_indices[class_name] = i
    for img in os.listdir(class_dir):
        image_paths.append(os.path.join(class_dir, img))
        labels.append(i)


# 转换为numpy数组
image_paths = np.array(image_paths)
labels = np.array(labels)

from sklearn.model_selection import KFold
import pandas as pd
import os
import numpy as np
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, Callback, CSVLogger
from keras.models import load_model
from tensorflow.keras import backend as K
import random
import numpy as np
import tensorflow as tf
from PIL import Image, ImageEnhance
from sklearn.model_selection import KFold
import os
from sklearn.model_selection import StratifiedKFold
import shutil
from keras.utils import custom_object_scope


# ============ 从这里设置开始训练的fold ============
# 手动设置从第几折开始训练
# 例如：start_fold = 1 表示从第1折开始训练
#       start_fold = 3 表示从第3折开始训练（跳过第1-2折）
start_fold = 4  # 请根据需要修改这个值
print(f"将从第 {start_fold} 折开始训练")
# ============ 设置结束 ============



def apply_class_specific_augmentation(img_path, label, num_augmentations, base_seed):
    """
    根据类别应用不同的增强策略
    """
    with Image.open(img_path) as image:
        if image.mode != 'RGB':
            image = image.convert('RGB')

        augmented_images = []

        for aug_idx in range(num_augmentations):
            # 为每个增强创建确定性种子
            rng = random.Random(base_seed + aug_idx * 1000)

            # 基础变换
            img = image.copy()

            # 根据类别应用不同的增强强度
            if label == 1:  # ADHD hyperactive (最重要)
                # 最强的增强：多种变换组合
                # 1. 随机旋转 (-30度到30度)
                if rng.random() > 0.5:
                    angle = rng.uniform(-30, 30)
                    img = img.rotate(angle, resample=Image.BILINEAR, expand=False)

                # 2. 随机翻转
                if rng.random() > 0.5:
                    img = img.transpose(Image.FLIP_LEFT_RIGHT)
                if rng.random() > 0.5:
                    img = img.transpose(Image.FLIP_TOP_BOTTOM)

                # 3. 颜色增强（更强的变化）
                brightness_factor = rng.uniform(0.7, 1.3)
                enhancer = ImageEnhance.Brightness(img)
                img = enhancer.enhance(brightness_factor)

                contrast_factor = rng.uniform(0.7, 1.3)
                enhancer = ImageEnhance.Contrast(img)
                img = enhancer.enhance(contrast_factor)

                sharpness_factor = rng.uniform(0.7, 1.3)
                enhancer = ImageEnhance.Sharpness(img)
                img = enhancer.enhance(sharpness_factor)

                # 4. 颜色平衡调整
                color_factor = rng.uniform(0.8, 1.2)
                enhancer = ImageEnhance.Color(img)
                img = enhancer.enhance(color_factor)

            elif label == 0:  # ADHD combined
                # 中等强度的增强
                if rng.random() > 0.5:
                    img = img.transpose(Image.FLIP_LEFT_RIGHT)

                brightness_factor = rng.uniform(0.8, 1.2)
                enhancer = ImageEnhance.Brightness(img)
                img = enhancer.enhance(brightness_factor)

                contrast_factor = rng.uniform(0.8, 1.2)
                enhancer = ImageEnhance.Contrast(img)
                img = enhancer.enhance(contrast_factor)

            elif label == 2:  # ADHD inattentive
                # 中等强度，类似ADHD combined
                if rng.random() > 0.5:
                    img = img.transpose(Image.FLIP_LEFT_RIGHT)

                brightness_factor = rng.uniform(0.85, 1.15)
                enhancer = ImageEnhance.Brightness(img)
                img = enhancer.enhance(brightness_factor)

            elif label == 3:  # ASD
                # 轻微增强，保持特征
                if rng.random() > 0.7:  # 30%概率增强
                    img = img.transpose(Image.FLIP_LEFT_RIGHT)

                brightness_factor = rng.uniform(0.9, 1.1)
                enhancer = ImageEnhance.Brightness(img)
                img = enhancer.enhance(brightness_factor)

            # neurotypical (label=4) 不做增强
            # elif label == 4:  # neurotypical
            #     if rng.random() > 0.8:  # 20%概率
            #         img = img.transpose(Image.FLIP_LEFT_RIGHT)
            #     brightness_factor = rng.uniform(0.98, 1.02)
            #     img = ImageEnhance.Brightness(img).enhance(brightness_factor)

            augmented_images.append(img)

        return augmented_images






# class SaveBestModelOnly(Callback):
#     def __init__(self, save_dir, fold_num):
#         super(SaveBestModelOnly, self).__init__()
#         self.save_dir = save_dir
#         self.fold_num = fold_num
#         self.best_val_loss = float('inf')  # 初始化为无穷大
#         self.best_model_path = os.path.join(save_dir, f'fold_{fold_num}_best_model.h5')
#         os.makedirs(save_dir, exist_ok=True)  # 确保目录存在

#     def on_epoch_end(self, epoch, logs=None):
#         current_val_loss = logs.get('val_loss')

#         if current_val_loss is not None and current_val_loss < self.best_val_loss:
#             # 更新最佳损失值
#             self.best_val_loss = current_val_loss

#             # 直接覆盖保存模型
#             self.model.save(self.best_model_path)
#             print(f'Fold {self.fold_num} - Epoch {epoch+1}: '
#                   f'val_loss改善为{current_val_loss:.6f}, 已保存最佳模型')

# 自定义回调：每个epoch保存模型
class SaveModelEachEpoch(Callback):
    def __init__(self, save_dir, fold_num):
        super(SaveModelEachEpoch, self).__init__()
        self.save_dir = save_dir
        self.fold_num = fold_num

    def on_epoch_end(self, epoch, logs=None):
        # 创建每个epoch的模型保存路径
        epoch_model_path = os.path.join(
            self.save_dir,
            f'fold_{self.fold_num}_epoch_{epoch+1:03d}.h5'
        )
        # 保存模型
        self.model.save(epoch_model_path)
        print(f'Fold {self.fold_num} - Epoch {epoch+1}: 模型已保存至 {epoch_model_path}')


# # 自定义回调：记录每个epoch的详细指标
# class MetricsLogger(Callback):
#     def __init__(self, save_dir, fold_num, val_generator):
#         super(MetricsLogger, self).__init__()
#         self.save_dir = save_dir
#         self.fold_num = fold_num
#         self.val_generator = val_generator
#         self.metrics_history = []

#     def on_epoch_end(self, epoch, logs=None):
#         # 获取当前学习率
#         current_lr = K.get_value(self.model.optimizer.learning_rate)

#         # 获取训练集指标（从logs中获取）
#         train_loss = logs.get('loss', 0)
#         train_accuracy = logs.get('accuracy', 0)
#         train_precision = logs.get('precision', 0)
#         train_recall = logs.get('recall', 0)

#         # 计算训练集F1分数
#         train_f1 = 0
#         if train_precision + train_recall > 0:
#             train_f1 = 2 * (train_precision * train_recall) / (train_precision + train_recall)

#         # 获取验证集指标（从logs中获取）
#         val_loss = logs.get('val_loss', 0)
#         val_accuracy = logs.get('val_accuracy', 0)
#         val_precision = logs.get('val_precision', 0)
#         val_recall = logs.get('val_recall', 0)

#         # 计算验证集F1分数
#         val_f1 = 0
#         if val_precision + val_recall > 0:
#             val_f1 = 2 * (val_precision * val_recall) / (val_precision + val_recall)

#         # 记录指标
#         epoch_metrics = {
#             'epoch': epoch + 1,
#             'fold': self.fold_num,
#             'learning_rate': current_lr,

#             # 训练集指标
#             'train_loss': train_loss,
#             'train_accuracy': train_accuracy,
#             'train_precision': train_precision,
#             'train_recall': train_recall,
#             'train_f1': train_f1,

#             # 验证集指标
#             'val_loss': val_loss,
#             'val_accuracy': val_accuracy,
#             'val_precision': val_precision,
#             'val_recall': val_recall,
#             'val_f1': val_f1
#         }

#         self.metrics_history.append(epoch_metrics)

#         # 打印当前epoch的指标
#         print(f'Fold {self.fold_num} - Epoch {epoch+1}: '
#               f'LR={current_lr:.6f}, '
#               f'Train Loss={train_loss:.4f}, Train Acc={train_accuracy:.4f}, '
#               f'Val Loss={val_loss:.4f}, Val Acc={val_accuracy:.4f}')

#     def on_train_end(self, logs=None):
#         # 训练结束时，将指标保存为CSV文件
#         if self.metrics_history:
#             metrics_df = pd.DataFrame(self.metrics_history)

#             # 按列排序，让显示更清晰
#             columns_order = [
#                 'epoch', 'fold', 'learning_rate',
#                 'train_loss', 'train_accuracy', 'train_precision', 'train_recall', 'train_f1',
#                 'val_loss', 'val_accuracy', 'val_precision', 'val_recall', 'val_f1'
#             ]
#             metrics_df = metrics_df[columns_order]

#             # 保存为CSV文件
#             csv_filename = os.path.join(self.save_dir, f'fold_{self.fold_num}_epoch_metrics.csv')
#             metrics_df.to_csv(csv_filename, index=False)
#             print(f'Fold {self.fold_num}: 每个epoch的指标已保存至 {csv_filename}')


# 创建每个epoch模型保存的目录
epoch_models_dir = '/content/drive/My Drive/ASD ADHD revision/Best model_Best parameter/final_result/epoch_models_ADBrainNet_final'
if not os.path.exists(epoch_models_dir):
    os.makedirs(epoch_models_dir)
    print(f"创建epoch模型目录: {epoch_models_dir}")

# 创建每个epoch指标保存的目录
epoch_metrics_dir = '/content/drive/My Drive/ASD ADHD revision/Best model_Best parameter/final_result/epoch_metrics_ADBrainNet_final'
if not os.path.exists(epoch_metrics_dir):
    os.makedirs(epoch_metrics_dir)
    print(f"创建epoch指标目录: {epoch_metrics_dir}")


# 数据生成器
datagen = ImageDataGenerator(rescale=1./255)

# 设置全局随机种子以确保可复现性
random.seed(42)
np.random.seed(42)
tf.random.set_seed(42)
os.environ['PYTHONHASHSEED'] = str(42)


# 添加KFold初始化
kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
# 存储每折的结果
fold_no = 1
fold_results = []

# 5折交叉验证
for train_idx, val_idx in kfold.split(image_paths, labels):
    # 跳过start_fold之前的fold
    if fold_no < start_fold:
        print(f'\n{"="*50}')
        print(f'跳过 Fold {fold_no} (从 Fold {start_fold} 开始)')
        print(f'{"="*50}')
        fold_no += 1
        continue

    print(f'\n{"="*50}')
    print(f'Training Fold {fold_no}')
    print(f'{"="*50}')

    # 创建临时目录用于当前折的训练和验证
    temp_train_dir = f'/content/fold_{fold_no}_train'
    temp_val_dir = f'/content/fold_{fold_no}_val'

    # 删除已存在的目录（避免数据累积）
    if os.path.exists(temp_train_dir):
        shutil.rmtree(temp_train_dir)
    if os.path.exists(temp_val_dir):
        shutil.rmtree(temp_val_dir)

    # 创建目录结构
    for class_name in classes:
        os.makedirs(os.path.join(temp_train_dir, class_name), exist_ok=True)
        os.makedirs(os.path.join(temp_val_dir, class_name), exist_ok=True)

    # 复制训练数据 - 只复制train_idx对应的数据，并对少数类进行可复现的增强
    # 因为之前的数据处理只涉及某一类，所以效果不明显，所以我们现在对所有的少数类都做不同程度的增强。
    for idx in train_idx:
        img_path = image_paths[idx]
        label = labels[idx]
        class_name = classes[label]

        # 复制原始图像
        shutil.copy2(img_path, os.path.join(temp_train_dir, class_name))

        # 根据类别决定增强倍数
        if label == 1:  # ADHD hyperactive - 最强增强，最多变体
            num_augmentations = 15
        elif label == 0:  # ADHD combined
            num_augmentations = 4
        elif label == 2:  # ADHD inattentive
            num_augmentations = 3
        elif label == 3:  # ASD
            num_augmentations = 2  # 轻微增强
        else:  # neurotypical
            num_augmentations = 1
            continue

        # 应用类别特定的增强
        base_seed = int(42 * 1000000 + idx * 10000 + fold_no * 1000 + label * 100)
        augmented_images = apply_class_specific_augmentation(
            img_path, label, num_augmentations, base_seed
        )

        # 保存增强后的图像
        for aug_idx, aug_img in enumerate(augmented_images):
            original_filename = os.path.basename(img_path)
            transformed_file_name = os.path.splitext(original_filename)[0] + f'_aug{aug_idx}.jpg'
            save_path = os.path.join(temp_train_dir, class_name, transformed_file_name)
            aug_img.save(save_path, 'png')

    # 复制验证数据 - 只复制val_idx对应的数据，不增强
    for idx in val_idx:
        img_path = image_paths[idx]
        label = labels[idx]
        class_name = classes[label]
        shutil.copy2(img_path, os.path.join(temp_val_dir, class_name))

    # 创建数据生成器
    train_generator = datagen.flow_from_directory(
        temp_train_dir,
        target_size=(64, 64),
        batch_size=64,
        class_mode='categorical'
    )

    val_generator = datagen.flow_from_directory(
        temp_val_dir,
        target_size=(64, 64),
        batch_size=64,
        class_mode='categorical',
        shuffle=False
    )

    # 创建模型
    model = build_cnn_model()


    # ####################################################################################
    # # ==================== 保留你的SENetLayer ====================
    # class SENetLayer(Layer):
    #     def __init__(self, ratio=16, **kwargs):
    #         super(SENetLayer, self).__init__(**kwargs)
    #         self.ratio = ratio

    #     def build(self, input_shape):
    #         channel_axis = 1 if K.image_data_format() == "channels_first" else -1
    #         channel_count = input_shape[channel_axis]

    #         self.global_avg_pool = GlobalAveragePooling2D()
    #         self.dense_1 = Dense(channel_count // self.ratio, activation='relu',
    #                             kernel_regularizer=l2(1e-5), use_bias=False)
    #         self.dense_2 = Dense(channel_count, activation='sigmoid',
    #                             kernel_regularizer=l2(1e-5), use_bias=False)
    #         self.multiply = Multiply()
    #         super(SENetLayer, self).build(input_shape)

    #     def call(self, inputs):
    #         se_feature = self.global_avg_pool(inputs)
    #         se_feature = self.dense_1(se_feature)
    #         se_feature = self.dense_2(se_feature)
    #         x = self.multiply([inputs, se_feature])
    #         return x

    #     def get_config(self):
    #         config = super().get_config()
    #         config.update({"ratio": self.ratio})
    #         return config

    # # ==================== 新增：增强的残差注意力块 ====================
    # class EnhancedResidualBlock(Layer):
    #     """结合残差连接和多尺度特征的增强块"""
    #     def __init__(self, filters, kernel_size=3, use_se=True, **kwargs):
    #         super(EnhancedResidualBlock, self).__init__(**kwargs)
    #         self.filters = filters
    #         self.kernel_size = kernel_size
    #         self.use_se = use_se

    #     def build(self, input_shape):
    #         # 主路径：两个卷积层
    #         self.conv1 = Conv2D(self.filters, self.kernel_size, padding='same',
    #                            kernel_regularizer=l2(1e-5))
    #         self.bn1 = BatchNormalization()

    #         self.conv2 = Conv2D(self.filters, self.kernel_size, padding='same',
    #                            kernel_regularizer=l2(1e-5))
    #         self.bn2 = BatchNormalization()

    #         # 多尺度特征提取
    #         self.conv3x3 = Conv2D(self.filters//4, 3, padding='same')
    #         self.conv5x5 = Conv2D(self.filters//4, 5, padding='same')
    #         self.conv1x1 = Conv2D(self.filters//2, 1, padding='same')

    #         # ========== 新增：在这里创建缺失的层 ==========
    #         # 多尺度特征的BN和激活
    #         self.bn_ms = BatchNormalization()
    #         self.activation_ms = Activation('relu')

    #         # 合并多尺度特征
    #         self.concat = Concatenate()
    #         self.add_ms = Add()  # 用于合并多尺度特征

    #         # 注意力
    #         if self.use_se:
    #             self.se = SENetLayer(ratio=16)

    #         # 快捷连接
    #         self.shortcut_conv = Conv2D(self.filters, 1, padding='same')
    #         self.shortcut_bn = BatchNormalization()

    #         # ========== 新增：残差合并层 ==========
    #         self.add_residual = Add()
    #         self.activation_out = Activation('relu')

    #         super().build(input_shape)

    #     def call(self, inputs):
    #         # 主路径
    #         x = self.conv1(inputs)
    #         x = self.bn1(x)
    #         x = Activation('relu')(x)

    #         x = self.conv2(x)
    #         x = self.bn2(x)

    #         # 多尺度特征
    #         branch1 = self.conv3x3(x)
    #         branch2 = self.conv5x5(x)
    #         branch3 = self.conv1x1(x)

    #         # 合并多尺度特征
    #         multi_scale = self.concat([branch1, branch2, branch3])
    #         multi_scale = self.bn_ms(multi_scale)
    #         multi_scale = self.activation_ms(multi_scale)

    #         # 与主路径融合 - 使用在build中创建的层
    #         x = self.add_ms([x, multi_scale])

    #         # SE注意力
    #         if self.use_se:
    #             x = self.se(x)

    #         # 残差连接
    #         shortcut = self.shortcut_conv(inputs)
    #         shortcut = self.shortcut_bn(shortcut)

    #         # 最终输出 - 使用在build中创建的层
    #         output = self.add_residual([x, shortcut])
    #         output = self.activation_out(output)

    #         return output

    #     def get_config(self):
    #         config = super().get_config()
    #         config.update({
    #             'filters': self.filters,
    #             'kernel_size': self.kernel_size,
    #             'use_se': self.use_se
    #         })
    #         return config

    # # 使用custom_object_scope加载模型
    # with custom_object_scope({
    #     'EnhancedResidualBlock': EnhancedResidualBlock,
    #     'SENetLayer': SENetLayer
    # }):
    #     model = load_model('/content/drive/My Drive/ASD ADHD revision/final dataset1/epoch_models_ADBrainNet_augmentation_enhancer/fold_1_best_model.h5')
    # #########################################################################







    #model = load_model('/content/drive/My Drive/ASD ADHD revision/final dataset1/epoch_models_ADBrainNet_augmentation_enhancer/fold_1_best_model.h5')

    # model.compile(optimizer=optimizers.Adam(learning_rate=0.00004),
    #               loss=losses.categorical_crossentropy,
    #               metrics=[metrics.CategoricalAccuracy(), metrics.Precision(), metrics.Recall(),
    #                       ])

    # 创建每个epoch保存模型的自定义回调
    save_each_epoch = SaveModelEachEpoch(
        save_dir=epoch_models_dir,
        fold_num=fold_no
    )

    # # 创建保存最优模型的自定义回调
    # save_best_model = SaveBestModelOnly(
    # save_dir=epoch_models_dir,
    # fold_num=fold_no
    # )

    # # 创建记录每个epoch指标的自定义回调
    # metrics_logger = MetricsLogger(
    #     save_dir=epoch_metrics_dir,
    #     fold_num=fold_no,
    #     val_generator=val_generator
    # )

    # 创建CSVLogger回调来记录每个epoch的指标
    csv_logger = CSVLogger(
      os.path.join(epoch_metrics_dir, f'fold_{fold_no}_epoch_metrics.csv'),
      separator=',',
      append=True  # 使用追加模式
    )

    # 设置回调函数
    class_weights = {0: 2.0, 1: 3.5, 2: 2.5, 3: 1.5, 4: 1.5}
    #initial_val_weights = {0: 20, 1: 100, 2: 15, 3: 5, 4: 0.05}

    early_stopping = EarlyStopping(monitor='val_loss', patience=20, verbose=1, restore_best_weights=True)
    lr_reduction = ReduceLROnPlateau(monitor='val_loss', patience=5, verbose=1, factor=0.2)

    # 训练模型
    history = model.fit(
        train_generator,
        class_weight=class_weights,
        steps_per_epoch=math.ceil(train_generator.samples / train_generator.batch_size),
        epochs=100,
        validation_data=val_generator,
        validation_steps=math.ceil(val_generator.samples / val_generator.batch_size),
        #AdjustValidationClassWeights(val_generator, initial_val_weights),
        callbacks=[
            lr_reduction,
            early_stopping,
            save_each_epoch,      # 添加每个epoch保存模型的回调
            csv_logger        # 添加记录每个epoch指标的回调
        ],
        verbose=2
    )

    # 评估模型
    scores = model.evaluate(val_generator, verbose=0)

    # 使用字典格式保存结果，便于转换为CSV
    fold_result = {
        'fold': fold_no,
        'val_loss': scores[0],
        'val_accuracy': scores[1],
        'val_precision': scores[2],
        'val_recall': scores[3],
        'val_f1': 2 * (scores[2] * scores[3]) / (scores[2] + scores[3]) if (scores[2] + scores[3]) > 0 else 0,
        'total_epochs': len(history.history['val_loss'])
    }
    fold_results.append(fold_result)

    # 正确打印所有指标
    print(f'\nFold {fold_no} 最终评估结果:')
    print(f'Val Loss: {scores[0]:.4f}, '
          f'Val Accuracy: {scores[1]:.4f}, '
          f'Val Precision: {scores[2]:.4f}, '
          f'Val Recall: {scores[3]:.4f}')

    # 计算并打印F1分数
    precision = scores[2]
    recall = scores[3]
    f1_score = 2 * (precision * recall) / (precision + recall) if (precision + recall) > 0 else 0
    print(f'Val F1 Score: {f1_score:.4f}')
    print(f'Fold {fold_no} 训练了 {len(history.history["val_loss"])} 个epoch')

    # 清理临时目录
    shutil.rmtree(temp_train_dir)
    shutil.rmtree(temp_val_dir)

    fold_no += 1

# 打印汇总结果（只针对本次运行的fold）
if fold_results:
    results_df = pd.DataFrame(fold_results)

    print("\n" + "=" * 80)
    print(f"本次运行的Fold汇总结果 (Fold {start_fold} 到 {fold_no-1}):")
    print("=" * 80)
    print(f"平均验证损失: {results_df['val_loss'].mean():.4f} ± {results_df['val_loss'].std():.4f}")
    print(f"平均验证准确率: {results_df['val_accuracy'].mean():.4f} ± {results_df['val_accuracy'].std():.4f}")
    print(f"平均验证精确率: {results_df['val_precision'].mean():.4f} ± {results_df['val_precision'].std():.4f}")
    print(f"平均验证召回率: {results_df['val_recall'].mean():.4f} ± {results_df['val_recall'].std():.4f}")
    print(f"平均验证F1分数: {results_df['val_f1'].mean():.4f} ± {results_df['val_f1'].std():.4f}")
    print(f"平均训练epoch数: {results_df['total_epochs'].mean():.1f} ± {results_df['total_epochs'].std():.1f}")

# 打印每个epoch模型保存的统计信息
print("\n" + "=" * 80)
print("每个epoch模型保存统计:")
print("=" * 80)
print(f"每个epoch的模型保存在: {epoch_models_dir}")
print(f"命名格式: fold_X_epoch_YYY.h5 (X=折号, YYY=epoch号，补零到3位)")
print(f"示例: fold_1_epoch_001.h5, fold_1_epoch_002.h5, ..., fold_1_epoch_100.h5")

# 打印每个epoch指标保存的统计信息
print("\n" + "=" * 80)
print("每个epoch指标保存统计:")
print("=" * 80)
print(f"每个epoch的指标保存在: {epoch_metrics_dir}")
print(f"命名格式: fold_X_epoch_metrics.csv (X=折号)")
# print(f"指标包括: epoch, fold, learning_rate, "
#       f"train_loss, train_accuracy, train_precision, train_recall, train_f1, "
#       f"val_loss, val_accuracy, val_precision, val_recall, val_f1")
print(f"CSVLogger会自动记录: epoch, loss, accuracy, precision, recall, val_loss, val_accuracy, val_precision, val_recall, lr")
print(f"注意: CSVLogger默认不记录F1分数，需要后续计算")
print(f"每个fold的训练过程中每个epoch的指标都会被记录并保存")

# 统计并显示实际保存的模型文件数量
import glob
model_files = glob.glob(os.path.join(epoch_models_dir, 'fold_*_epoch_*.h5'))
metrics_files = glob.glob(os.path.join(epoch_metrics_dir, 'fold_*_epoch_metrics.csv'))
print(f"\n当前保存的模型文件总数: {len(model_files)}")
print(f"当前保存的指标文件总数: {len(metrics_files)}")

# 保存fold_results到epoch_metrics_dir目录作为最终结果汇总
if fold_results:
    final_results_df = pd.DataFrame(fold_results)
    summary_row = {
        'fold': f'Mean ± Std (Fold {start_fold} to {fold_no-1})',
        'val_loss': f"{results_df['val_loss'].mean():.4f} ± {results_df['val_loss'].std():.4f}",
        'val_accuracy': f"{results_df['val_accuracy'].mean():.4f} ± {results_df['val_accuracy'].std():.4f}",
        'val_precision': f"{results_df['val_precision'].mean():.4f} ± {results_df['val_precision'].std():.4f}",
        'val_recall': f"{results_df['val_recall'].mean():.4f} ± {results_df['val_recall'].std():.4f}",
        'val_f1': f"{results_df['val_f1'].mean():.4f} ± {results_df['val_f1'].std():.4f}",
        'total_epochs': f"{results_df['total_epochs'].mean():.1f} ± {results_df['total_epochs'].std():.1f}"
    }
    final_results_df = pd.concat([final_results_df, pd.DataFrame([summary_row])], ignore_index=True)

    # 保存到epoch_metrics_dir目录
    csv_filename = os.path.join(epoch_metrics_dir, f'cross_validation_fold_{start_fold}_to_{fold_no-1}_results.csv')
    final_results_df.to_csv(csv_filename, index=False)
    print(f"\n本次运行的交叉验证结果已保存至: {csv_filename}")

